development:
  adapter: postgresql
  encoding: unicode
  database: test_app_dev
  pool: 5
  username: postgres
  password: admin123
test:
  adapter: postgresql
  encoding: unicode
  database: test_app_test
  pool: 5
  username: myapp
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: test_app_prod
  pool: 5
  username: myapp
  password: